security:
  oauth2:
    client:
      clientId: fms-reports-service
      clientSecret: 12345
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
server:
  servlet:
    context-path: /reports
  port: 8000

feign:
  hystrix:
    enabled: true
    
spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
